Note how numpy matrices are written by columns, sympy by rows

In [1]:
import numpy as np

from sympy import *
init_printing(use_unicode=True)

In [2]:
v = np.array([4, 53])
A = np.array([[3, 5, 4], [1, 3, 1]])
np.matmul(v, A)

array([ 65, 179,  69])

In [3]:
v = Matrix([4, 53])
A = Matrix([[3, 1], [5, 3], [4, 1]])
A*v

⎡65 ⎤
⎢   ⎥
⎢179⎥
⎢   ⎥
⎣69 ⎦

Below I will begin testing the rectangular cipher and middle nonlinear function for homomorphic properties.  I immidiately show that the homomorphic properties and cipher works without the middle functions

In [51]:
message = np.array([3, 4, 1])
key1 = np.random.randint(0, 20, (len(message), 6))
key2 = np.random.randint(0, 20, (key1.shape[1], 8))
key2inv = np.matmul(key2.T, np.linalg.inv(np.matmul(key2, key2.T)))
key1inv = np.matmul(key1.T, np.linalg.inv(np.matmul(key1, key1.T)))

ciphertext = np.matmul(message, key1)
ciphertext

array([83, 57, 66, 95, 74, 91])

In [52]:
ciphertext = np.matmul(ciphertext, key2)
ciphertext

array([4472, 3777, 3575, 6058, 2940, 4274, 4064, 3562])

In [53]:
ciphertext *= 2
ciphertext

array([ 8944,  7554,  7150, 12116,  5880,  8548,  8128,  7124])

In [54]:
plaintext = np.matmul(ciphertext, key2inv)
plaintext

array([ 166.,  114.,  132.,  190.,  148.,  182.])

In [55]:
plaintext = np.matmul(plaintext, key1inv)
plaintext

array([ 6.,  8.,  2.])

Now I try to put everything together and with the middle functions

In [58]:
message = np.array([3, 4, 1])
key1 = np.random.randint(0, 20, (len(message), 6))
key2 = np.random.randint(0, 20, (key1.shape[1], 8))

def encrypt(message, key1, key2):
    ciphertext = np.matmul(message, key1)
    ciphertext = (ciphertext * 4) + 6
    ciphertext = np.matmul(ciphertext, key2)
    return ciphertext
                         
def decrypt(ciphertext, key1, key2):
    key2inv = np.matmul(key2.T, np.linalg.inv(np.matmul(key2, key2.T)))
    key1inv = np.matmul(key1.T, np.linalg.inv(np.matmul(key1, key1.T)))
    plaintext = np.matmul(ciphertext, key2inv)
    plaintext = (ciphertext * .25) - 6
    plaintext = np.matmul(plaintext, key1inv)
    return plaintext

ciphertext = encrypt(message, key1, key2)
print(ciphertext)
ciphertext *= 2
plaintext = decrypt(ciphertext, key1, key2)

[14726 19600 20800 16818 16764 25474 20756 19300]


ValueError: shapes (8,) and (6,3) not aligned: 8 (dim 0) != 6 (dim 0)